export {Home} from '../pages/Home';
export {Error} from '../pages/Error';
export {AboutUs} from './AboutUs';
export {Contact} from '../pages/Contact'
export {Login} from './users/Login';
export {Register} from  './users/Register';
export {Profile} from './users/Profile'
export {ForgotPassword} from './users/ForgotPassword';
export {ResetPassword} from './users/ResetPassword';
export {Activate} from './users/Activate'
export {Cart} from './users/Cart'
export {Shop} from './Shop'
export {AdminLogin} from './admin/AdminLogin';
export {AdminDashboard} from './admin/AdminDashboard'
export {Product} from './Product'
export {Search} from './Search'
export {ShippingInfo} from './Info/ShippingInfo'